init:
  - echo %PATH%
  # We use a clean PATH to avoid interferences with the hundreds of installed programs.
  - set PATH=c:/Program Files/Git/cmd;c:/ProgramData/chocolatey/bin;c:/Program Files (x86)/Inno Setup 5;c:/Windows/system32;C:/Windows/System32/WindowsPowerShell/v1.0
  - set PATH=C:/ruby%build_ruby%/bin;%PATH%
  - echo %PATH%
  - ruby --version

install:
  - choco install -y InnoSetup

build_script:
  # Remove broken pkg files from cache
  - c:/msys64/usr/bin/rm -f c:/msys64/var/cache/pacman/pkg/{pacman-mirrors}*
  # Build the installer
  - rake ri:ruby-%target_ruby%-%arch% & c:/msys64/usr/bin/gpgconf --homedir /etc/pacman.d/gnupg --kill all

  # Reuse installed ruby for RubyInstaller-Devkit
  - c:/msys64/usr/bin/mkdir -p packages/ri-msys/recipes/
  - c:/msys64/usr/bin/cp -a packages/ri/recipes/unpack packages/ri-msys/recipes/
  # Remove broken pkg files from cache
  - c:/msys64/usr/bin/rm -f c:/msys64/var/cache/pacman/pkg/{autoconf,automake,bash-completion,ca-certificates}*
  # Build the RubyInstaller-Devkit installer
  - rake ri-msys:ruby-%target_ruby%-%arch%:installer-inno

test_script:
  # Run the built Ruby installer and install to c:/ri2-ruby
  - ruby -e "Dir['packages/ri/recipes/installer-inno/rubyinstaller-%target_ruby%*-%arch%.exe'].each{|f| system(f, '/verysilent', '/dir=c:/ri2-ruby', '/tasks=assocfiles,modpath,defaultutf8')}"
  # Activate the environment variables set by the installer, but exclude
  # git's /usr/bin, because it conflicts with one RubyInstaller test.
  - ps: $env:PATH = [Environment]::GetEnvironmentVariable("PATH","Machine") -replace ";C:\\Program Files\\Git\\usr\\bin" -replace ";C:\\Ruby193\\bin"
  - ps: $env:RUBYOPT = [Environment]::GetEnvironmentVariable("RUBYOPT","Machine")
  - echo %PATH%
  - echo %RUBYOPT%
  - ridk version
  # Install dependent gems
  - IF "%target_ruby%" LSS "2.6" ( gem install bundler )
  - bundle install
  # Run all tests against the new installed Ruby
  - rake test
  # Verify that the used CA list is still the latest.
  - rake ssl:update_check
  # Enable MSYS2 commands in cmd
  - ridk enable

  # Run the Ruby Spec Suite
  - IF DEFINED run_ruby_spec ( IF NOT DEFINED APPVEYOR_REPO_TAG_NAME (
      git clone --depth 1 https://github.com/ruby/mspec &&
      git clone --depth 1 https://github.com/ruby/spec &&
      env --unset=RUBYOPT ruby -C spec ../mspec/bin/mspec -j --exclude "Socket.getnameinfo using IPv4 using a 3 element Array as the first argument without custom flags returns an Array containing the hostname and service name" --exclude "Socket.getifaddrs each returned Socket::Ifaddr has an interface index"
    ))

  # Run the MRI copy of Ruby Spec Suite
  - IF DEFINED run_mri_spec ( IF NOT DEFINED APPVEYOR_REPO_TAG_NAME (
      git clone --depth 1 https://github.com/ruby/ruby -b %run_mri_spec% &&
      env --unset=RUBYOPT ruby -C ruby/spec/ruby ../mspec/bin/mspec -j --exclude "Socket.getnameinfo using IPv4 using a 3 element Array as the first argument without custom flags returns an Array containing the hostname and service name"
    ))

  # Run upload to github (only on tag builds)
  - set DEPLOY_TAG=%APPVEYOR_REPO_TAG_NAME%
  - IF "%target_ruby%" EQU "head" (SET DEPLOY_TAG=rubyinstaller-head)
  - rake release:appveyor_upload -- packages/ri/recipes/installer-inno/%DEPLOY_TAG%*-%arch%.exe packages/ri/recipes/archive-7z/%DEPLOY_TAG%*-%arch%.7z packages/ri-msys/recipes/installer-inno/ruby*-%target_ruby%*-%arch%.exe

# Provide the rubyinstaller.exe files for download
artifacts:
  - path: packages/ri/recipes/installer-inno/ruby*-$(target_ruby)*-$(arch).exe
    name: Executable installer
  - path: packages/ri/recipes/archive-7z/ruby*-$(target_ruby)*-$(arch).7z
    name: Plain archive file
  - path: packages/ri-msys/recipes/installer-inno/ruby*-$(target_ruby)*-$(arch).exe
    name: Executable installer with MYS2

environment:
  GPGPASSWD:
    secure: /DELcKSZC+R4HdXgsqR1RtC+IrDZ3Xut/vzV/KgepE3M8OsjJtmWutN0+Jvc2Iv2
  DEPLOY_REPO_NAME: oneclick/rubyinstaller2
  DEPLOY_TOKEN:
    secure: HIQ7Ovn+zMKskPWhnlYGvQMvdLPlZB5lhn62wzw0AUSno8UfntuTgFmPvS1pUwOW
  matrix:
    - target_ruby: "2.5.3"
      arch: "x64"
      build_ruby: "24"
      MINGW_PACKAGE_PREFIX: "mingw-w64-x86_64"
      MSYSTEM: "MINGW64"
      run_ruby_spec: true

    - target_ruby: "2.5.3"
      arch: "x86"
      build_ruby: "24"
      MINGW_PACKAGE_PREFIX: "mingw-w64-i686"
      MSYSTEM: "MINGW32"
      run_ruby_spec: true

    - target_ruby: "head"
      arch: "x64"
      build_ruby: "24"
      MINGW_PACKAGE_PREFIX: "mingw-w64-x86_64"
      MSYSTEM: "MINGW64"
      run_mri_spec: trunk

    - target_ruby: "2.4.5"
      arch: "x64"
      build_ruby: "23"
      MINGW_PACKAGE_PREFIX: "mingw-w64-x86_64"
      MSYSTEM: "MINGW64"
      run_ruby_spec: true

    - target_ruby: "head"
      arch: "x86"
      build_ruby: "24"
      MINGW_PACKAGE_PREFIX: "mingw-w64-i686"
      MSYSTEM: "MINGW32"
      run_mri_spec: trunk

    - target_ruby: "2.4.5"
      arch: "x86"
      build_ruby: "22"
      MINGW_PACKAGE_PREFIX: "mingw-w64-i686"
      MSYSTEM: "MINGW32"
      run_ruby_spec: true
